{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ace-mitre-engine.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ace-mitre-engine.labels" . | nindent 4 }}
{{- end }}
