apiVersion: v1
kind: Service
metadata:
  name: {{ include "ace-correlate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ace-correlate.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: health
      protocol: TCP
      name: http
  selector:
    {{- include "ace-correlate.selectorLabels" . | nindent 4 }}
