apiVersion: v1
kind: Service
metadata:
  name: {{ include "ace-normalize.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ace-normalize.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ace-normalize.selectorLabels" . | nindent 4 }}
  ports:
    - name: health
      port: {{ .Values.service.healthPort | default 8081 }}
      targetPort: health
      protocol: TCP
