apiVersion: v1
kind: Service
metadata:
  name: {{ include "ace-threat-intel.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ace-threat-intel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ace-threat-intel.selectorLabels" . | nindent 4 }}
