apiVersion: v1
kind: Service
metadata:
  name: {{ include "ace-ingest.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ace-ingest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ace-ingest.selectorLabels" . | nindent 4 }}
  ports:
    - name: health
      port: {{ .Values.service.healthPort | default 8080 }}
      targetPort: health
      protocol: TCP
    - name: syslog-tcp
      port: {{ .Values.service.syslogTCPPort | default 6514 }}
      targetPort: syslog-tcp
      protocol: TCP
    - name: syslog-udp
      port: {{ .Values.service.syslogUDPPort | default 514 }}
      targetPort: syslog-udp
      protocol: UDP
    {{- if .Values.protocols.wef.enabled }}
    - name: wef
      port: {{ .Values.service.wefPort | default 5985 }}
      targetPort: wef
      protocol: TCP
    {{- end }}
    {{- if .Values.protocols.k8sAudit.enabled }}
    - name: k8s-audit
      port: {{ .Values.service.k8sAuditPort | default 9443 }}
      targetPort: k8s-audit
      protocol: TCP
    {{- end }}
