{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ace-asset-inventory.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ace-asset-inventory.labels" . | nindent 4 }}
{{- end }}
